#!/usr/bin/env bash
# =============================================================================
# configure-vm.sh — Configure an OpenClaw instance on a provisioned VM
#
# Usage:
#   bash configure-vm.sh <telegram_bot_token> <api_key|ALL_INCLUSIVE> <gateway_token> [model]
#
# Arguments:
#   telegram_bot_token  — The user's Telegram bot token from @BotFather
#   api_key             — Anthropic API key, or 'ALL_INCLUSIVE' to use the
#                         platform-provided key (set via ANTHROPIC_API_KEY env var)
#   gateway_token       — UUID token for authenticating gateway requests
#                         (generated by InstaClaw backend)
#   model               — Claude model ID (optional, defaults to claude-sonnet-4-5-20250929)
#
# What it does:
#   1. Validates arguments
#   2. Encrypts API keys and bot token to disk (never stored in plaintext)
#   3. Writes ~/.openclaw/openclaw.json (references encrypted files)
#   4. Starts or restarts the OpenClaw gateway (bound to 127.0.0.1 only)
#   5. Waits for the health check endpoint to respond
#   6. Prints success or failure
#
# This script runs as the 'openclaw' user on the target VM.
# It is called over SSH by the InstaClaw backend (lib/ssh.ts).
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()   { echo -e "${GREEN}[✓]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
fail()  { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OPENCLAW_HOME="${HOME}"
OPENCLAW_DIR="${OPENCLAW_HOME}/openclaw"
CONFIG_DIR="${OPENCLAW_HOME}/.openclaw"
CREDS_DIR="${CONFIG_DIR}/creds"
CONFIG_FILE="${CONFIG_DIR}/openclaw.json"
ENCRYPTION_KEY_FILE="${CONFIG_DIR}/.vault_key"
GATEWAY_PORT=8080
CONTROL_UI_PORT=3000
# Gateway and control UI bind to localhost only — external access via Caddy
GATEWAY_BIND="127.0.0.1"
HEALTH_URL="http://127.0.0.1:${GATEWAY_PORT}/health"
HEALTH_TIMEOUT=60
HEALTH_INTERVAL=2

# ---------------------------------------------------------------------------
# Encryption helpers
# ---------------------------------------------------------------------------

# Encrypt a value and write it to a file. Uses AES-256-CBC with the per-VM
# vault key. The encrypted file is readable only by the openclaw user.
encrypt_to_file() {
  local plaintext="$1"
  local outfile="$2"

  if [[ ! -f "${ENCRYPTION_KEY_FILE}" ]]; then
    fail "Encryption key not found at ${ENCRYPTION_KEY_FILE}. Run install-openclaw.sh first."
  fi

  echo -n "${plaintext}" \
    | openssl enc -aes-256-cbc -salt -pbkdf2 -iter 100000 \
        -pass "file:${ENCRYPTION_KEY_FILE}" \
        -out "${outfile}"

  chmod 600 "${outfile}"
}

# Decrypt a file and print the plaintext to stdout.
decrypt_from_file() {
  local infile="$1"

  if [[ ! -f "${ENCRYPTION_KEY_FILE}" ]]; then
    fail "Encryption key not found at ${ENCRYPTION_KEY_FILE}."
  fi

  openssl enc -aes-256-cbc -d -salt -pbkdf2 -iter 100000 \
    -pass "file:${ENCRYPTION_KEY_FILE}" \
    -in "${infile}"
}

# ---------------------------------------------------------------------------
# 1. Validate arguments
# ---------------------------------------------------------------------------

if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <telegram_bot_token> <api_key|ALL_INCLUSIVE> <gateway_token>"
  echo ""
  echo "Arguments:"
  echo "  telegram_bot_token  Token from @BotFather (e.g. 123456789:ABC...)"
  echo "  api_key             Anthropic API key, or 'ALL_INCLUSIVE'"
  echo "  gateway_token       UUID for gateway auth (generated by InstaClaw)"
  exit 1
fi

TELEGRAM_BOT_TOKEN="$1"
API_KEY_ARG="$2"
GATEWAY_TOKEN="$3"
MODEL="${4:-claude-sonnet-4-5-20250929}"

# Validate Telegram token format
if [[ ! "${TELEGRAM_BOT_TOKEN}" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]]; then
  fail "Invalid Telegram bot token format. Expected: 123456789:ABCdef..."
fi

# Validate gateway token is non-empty
if [[ -z "${GATEWAY_TOKEN}" ]]; then
  fail "Gateway token cannot be empty."
fi

# Validate model against allowed list
ALLOWED_MODELS="claude-haiku-4-5-20251001 claude-sonnet-4-5-20250929 claude-opus-4-5-20250820 claude-opus-4-6"
model_valid=false
for m in ${ALLOWED_MODELS}; do
  if [[ "${MODEL}" == "${m}" ]]; then
    model_valid=true
    break
  fi
done
if [[ "${model_valid}" != true ]]; then
  warn "Unknown model '${MODEL}', defaulting to claude-sonnet-4-5-20250929."
  MODEL="claude-sonnet-4-5-20250929"
fi

# Resolve API key
if [[ "${API_KEY_ARG}" == "ALL_INCLUSIVE" ]]; then
  API_MODE="all_inclusive"
  API_KEY="${ANTHROPIC_API_KEY:-}"
  if [[ -z "${API_KEY}" ]]; then
    warn "ANTHROPIC_API_KEY not set in environment. The container must have it configured."
    API_KEY="__platform_provided__"
  fi
else
  API_MODE="byok"
  API_KEY="${API_KEY_ARG}"
  if [[ -z "${API_KEY}" ]]; then
    fail "BYOK mode requires a non-empty API key."
  fi
fi

# Resolve proxy URL for all-inclusive mode (rate-limited proxy)
PROXY_URL="${ANTHROPIC_PROXY_URL:-}"

log "Configuration validated."
log "  Mode:     ${API_MODE}"
log "  Model:    ${MODEL}"
if [[ -n "${PROXY_URL}" ]]; then
  log "  Proxy:    ${PROXY_URL}"
fi
log "  Telegram: ${TELEGRAM_BOT_TOKEN:0:10}..."
log "  Gateway:  ${GATEWAY_TOKEN:0:8}..."

# ---------------------------------------------------------------------------
# 2. Encrypt credentials to disk
# ---------------------------------------------------------------------------

log "Encrypting credentials..."

mkdir -p "${CREDS_DIR}"
chmod 700 "${CREDS_DIR}"

# Encrypt each secret into its own file
encrypt_to_file "${TELEGRAM_BOT_TOKEN}" "${CREDS_DIR}/telegram_token.enc"
encrypt_to_file "${API_KEY}"             "${CREDS_DIR}/api_key.enc"
encrypt_to_file "${GATEWAY_TOKEN}"       "${CREDS_DIR}/gateway_token.enc"

log "Credentials encrypted to ${CREDS_DIR}/."

# Verify round-trip (decrypt and compare)
VERIFY_TOKEN=$(decrypt_from_file "${CREDS_DIR}/gateway_token.enc")
if [[ "${VERIFY_TOKEN}" != "${GATEWAY_TOKEN}" ]]; then
  fail "Encryption round-trip verification failed!"
fi

log "Encryption verification passed."

# ---------------------------------------------------------------------------
# 3. Write openclaw.json config (no plaintext secrets)
# ---------------------------------------------------------------------------

mkdir -p "${CONFIG_DIR}"

# The config file references encrypted credential files rather than
# storing secrets in plaintext. The gateway startup wrapper decrypts
# them into environment variables at launch time.
TEMP_CONFIG=$(mktemp "${CONFIG_DIR}/.openclaw.json.XXXXXX")

# Build optional proxy section for all-inclusive mode
PROXY_JSON=""
if [[ -n "${PROXY_URL}" ]]; then
  PROXY_JSON=$(cat <<PROXYEOF
  "proxy": {
    "enabled": true,
    "url": "${PROXY_URL}"
  },
PROXYEOF
)
fi

cat > "${TEMP_CONFIG}" <<CONFIGEOF
{
  "telegram": {
    "bot_token_file": "${CREDS_DIR}/telegram_token.enc"
  },
  "api": {
    "mode": "${API_MODE}",
    "key_file": "${CREDS_DIR}/api_key.enc"
  },
  "model": {
    "default": "${MODEL}"
  },
  ${PROXY_JSON}
  "gateway": {
    "token_file": "${CREDS_DIR}/gateway_token.enc",
    "port": ${GATEWAY_PORT},
    "bind": "${GATEWAY_BIND}"
  },
  "control_ui": {
    "port": ${CONTROL_UI_PORT},
    "bind": "${GATEWAY_BIND}"
  },
  "security": {
    "credentials_encrypted": true,
    "encryption_method": "aes-256-cbc",
    "vault_key_file": "${ENCRYPTION_KEY_FILE}"
  },
  "configured_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
CONFIGEOF

mv "${TEMP_CONFIG}" "${CONFIG_FILE}"
chmod 600 "${CONFIG_FILE}"

log "Config written to ${CONFIG_FILE} (secrets encrypted, not plaintext)."

# ---------------------------------------------------------------------------
# 3b. Generate self-signed TLS cert and load full Caddy config via admin API
# ---------------------------------------------------------------------------

# Get the VM's external IP for the certificate SAN
VM_IP=$(curl -s -4 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')

CERT_DIR="${CONFIG_DIR}/certs"
mkdir -p "${CERT_DIR}"

if [[ ! -f "${CERT_DIR}/cert.pem" ]]; then
  log "Generating self-signed TLS certificate for ${VM_IP}..."
  openssl req -x509 -newkey rsa:2048 \
    -keyout "${CERT_DIR}/key.pem" \
    -out "${CERT_DIR}/cert.pem" \
    -days 3650 -nodes \
    -subj "/CN=${VM_IP}" \
    -addext "subjectAltName=IP:${VM_IP}" 2>/dev/null
  chmod 644 "${CERT_DIR}/cert.pem" "${CERT_DIR}/key.pem"
  log "TLS certificate generated for IP ${VM_IP}."
else
  log "TLS certificate already exists."
fi

# Load complete Caddy config with inline PEM cert via admin API.
# This avoids filesystem permission issues (Caddy runs as a different user).
CERT_PEM=$(python3 -c "import json,sys; print(json.dumps(open('${CERT_DIR}/cert.pem').read()))")
KEY_PEM=$(python3 -c "import json,sys; print(json.dumps(open('${CERT_DIR}/key.pem').read()))")

log "Loading Caddy config with TLS cert via admin API..."
CADDY_RESULT=$(curl -sf -X POST http://localhost:2019/load \
  -H "Content-Type: application/json" \
  -d "{
  \"apps\": {
    \"http\": {
      \"servers\": {
        \"srv0\": {
          \"listen\": [\":443\"],
          \"tls_connection_policies\": [{\"certificate_selection\": {\"any_tag\": [\"self-signed\"]}}],
          \"routes\": [
            {\"handle\": [{\"handler\": \"headers\", \"response\": {\"deferred\": true, \"delete\": [\"Server\"], \"set\": {\"X-Content-Type-Options\": [\"nosniff\"], \"X-Frame-Options\": [\"DENY\"], \"Referrer-Policy\": [\"strict-origin-when-cross-origin\"], \"Strict-Transport-Security\": [\"max-age=31536000; includeSubDomains; preload\"]}}}]},
            {\"group\": \"g3\", \"match\": [{\"path\": [\"/webhook\"]}], \"handle\": [{\"handler\": \"subroute\", \"routes\": [{\"handle\": [{\"handler\": \"reverse_proxy\", \"upstreams\": [{\"dial\": \"127.0.0.1:${GATEWAY_PORT}\"}]}]}]}]},
            {\"group\": \"g3\", \"match\": [{\"path\": [\"/api/gateway/*\"]}], \"handle\": [{\"handler\": \"subroute\", \"routes\": [{\"match\": [{\"not\": [{\"header\": {\"X-Gateway-Token\": [\"*\"]}}]}], \"handle\": [{\"handler\": \"static_response\", \"status_code\": 401, \"body\": \"Missing gateway token\", \"close\": true}]}, {\"handle\": [{\"handler\": \"reverse_proxy\", \"upstreams\": [{\"dial\": \"127.0.0.1:${GATEWAY_PORT}\"}]}]}]}]},
            {\"group\": \"g3\", \"match\": [{\"path\": [\"/health\"]}], \"handle\": [{\"handler\": \"subroute\", \"routes\": [{\"handle\": [{\"handler\": \"reverse_proxy\", \"upstreams\": [{\"dial\": \"127.0.0.1:${GATEWAY_PORT}\"}]}]}]}]},
            {\"group\": \"g3\", \"handle\": [{\"handler\": \"subroute\", \"routes\": [{\"handle\": [{\"handler\": \"reverse_proxy\", \"upstreams\": [{\"dial\": \"127.0.0.1:${CONTROL_UI_PORT}\"}]}]}]}]}
          ]
        },
        \"srv1\": {
          \"listen\": [\":80\"],
          \"routes\": [{\"handle\": [{\"handler\": \"static_response\", \"status_code\": 301, \"headers\": {\"Location\": [\"https://{http.request.host}{http.request.uri}\"]}}]}]
        }
      }
    },
    \"tls\": {
      \"certificates\": {
        \"load_pem\": [{\"certificate\": ${CERT_PEM}, \"key\": ${KEY_PEM}, \"tags\": [\"self-signed\"]}]
      }
    }
  }
}" 2>&1)

if [[ $? -eq 0 ]]; then
  log "Caddy config loaded with TLS cert."
else
  warn "Caddy config load failed: ${CADDY_RESULT}"
  warn "HTTPS may not work. Telegram webhooks may fail."
fi

# ---------------------------------------------------------------------------
# 3c. Set Telegram webhook with self-signed certificate
# ---------------------------------------------------------------------------

log "Setting Telegram webhook with self-signed certificate..."
DECRYPTED_TG_TOKEN=$(decrypt_from_file "${CREDS_DIR}/telegram_token.enc")

WEBHOOK_RESULT=$(curl -sf \
  -F "url=https://${VM_IP}/webhook" \
  -F "certificate=@${CERT_DIR}/cert.pem" \
  "https://api.telegram.org/bot${DECRYPTED_TG_TOKEN}/setWebhook" 2>&1)

if echo "${WEBHOOK_RESULT}" | grep -q '"ok":true'; then
  log "Telegram webhook set with self-signed certificate."
else
  warn "Telegram webhook setup failed: ${WEBHOOK_RESULT}"
fi

unset DECRYPTED_TG_TOKEN

# ---------------------------------------------------------------------------
# 4. Start or restart the OpenClaw gateway (localhost only)
# ---------------------------------------------------------------------------

log "Starting OpenClaw gateway (bound to ${GATEWAY_BIND})..."

# Decrypt credentials into env vars for the container.
# These live only in the container's process memory — never on disk in plaintext.
DECRYPTED_TELEGRAM=$(decrypt_from_file "${CREDS_DIR}/telegram_token.enc")
DECRYPTED_API_KEY=$(decrypt_from_file "${CREDS_DIR}/api_key.enc")
DECRYPTED_GW_TOKEN=$(decrypt_from_file "${CREDS_DIR}/gateway_token.enc")

if [[ -f "${OPENCLAW_DIR}/docker-compose.yml" ]]; then
  cd "${OPENCLAW_DIR}"

  export TELEGRAM_BOT_TOKEN="${DECRYPTED_TELEGRAM}"
  export ANTHROPIC_API_KEY="${DECRYPTED_API_KEY}"
  export GATEWAY_TOKEN="${DECRYPTED_GW_TOKEN}"
  export GATEWAY_PORT="${GATEWAY_PORT}"
  export GATEWAY_BIND="0.0.0.0"
  export OPENCLAW_CONFIG="${CONFIG_FILE}"
  export CLAUDE_MODEL="${MODEL}"
  if [[ -n "${PROXY_URL}" ]]; then
    export ANTHROPIC_PROXY_URL="${PROXY_URL}"
  fi

  # Always use --force-recreate to pick up new env vars on reconfiguration
  log "Starting containers (force-recreate to apply new config)..."
  docker compose up -d --force-recreate

  log "Docker Compose project started."
else
  CONTAINER_NAME="openclaw-gateway"

  if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
    log "Stopping existing container '${CONTAINER_NAME}'..."
    docker stop "${CONTAINER_NAME}" 2>/dev/null || true
    docker rm "${CONTAINER_NAME}" 2>/dev/null || true
  fi

  # Write secrets to a temporary env file (avoids leaking in ps output)
  ENV_FILE=$(mktemp "${CONFIG_DIR}/.env.XXXXXX")
  chmod 600 "${ENV_FILE}"
  cat > "${ENV_FILE}" <<ENVEOF
TELEGRAM_BOT_TOKEN=${DECRYPTED_TELEGRAM}
ANTHROPIC_API_KEY=${DECRYPTED_API_KEY}
GATEWAY_TOKEN=${DECRYPTED_GW_TOKEN}
GATEWAY_PORT=${GATEWAY_PORT}
GATEWAY_BIND=0.0.0.0
CLAUDE_MODEL=${MODEL}
ANTHROPIC_PROXY_URL=${PROXY_URL}
ENVEOF

  # Bind ports to 127.0.0.1 only — external access goes through Caddy
  docker run -d \
    --name "${CONTAINER_NAME}" \
    --restart unless-stopped \
    -p "${GATEWAY_BIND}:${GATEWAY_PORT}:${GATEWAY_PORT}" \
    -p "${GATEWAY_BIND}:${CONTROL_UI_PORT}:${CONTROL_UI_PORT}" \
    -v "${CONFIG_DIR}:/home/openclaw/.openclaw:ro" \
    --env-file "${ENV_FILE}" \
    openclaw-gateway

  # Remove the temporary env file immediately after container starts
  rm -f "${ENV_FILE}"

  log "Container '${CONTAINER_NAME}' started (bound to ${GATEWAY_BIND})."
fi

# Clear decrypted values from shell memory
unset DECRYPTED_TELEGRAM DECRYPTED_API_KEY DECRYPTED_GW_TOKEN

# ---------------------------------------------------------------------------
# 5. Wait for health check
# ---------------------------------------------------------------------------

log "Waiting for health check at ${HEALTH_URL}..."

elapsed=0
healthy=false

while [[ ${elapsed} -lt ${HEALTH_TIMEOUT} ]]; do
  if curl -sf -o /dev/null -m 5 "${HEALTH_URL}" 2>/dev/null; then
    healthy=true
    break
  fi
  sleep "${HEALTH_INTERVAL}"
  elapsed=$((elapsed + HEALTH_INTERVAL))
  echo -n "."
done

echo ""

if [[ "${healthy}" == true ]]; then
  log "Health check passed in ${elapsed}s."
else
  fail "Health check failed after ${HEALTH_TIMEOUT}s. Gateway may still be starting."
fi

# ---------------------------------------------------------------------------
# 6. Print success
# ---------------------------------------------------------------------------

VM_IP=$(curl -s -4 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo "=============================================="
echo -e "${GREEN} OpenClaw instance configured!${NC}"
echo "=============================================="
echo ""
echo "  VM IP:          ${VM_IP}"
echo "  Gateway:        https://${VM_IP}/api/gateway (via Caddy)"
echo "  Control UI:     https://${VM_IP}/ (via Caddy)"
echo "  API Mode:       ${API_MODE}"
echo "  Model:          ${MODEL}"
echo "  Health:         OK"
echo "  Credentials:    Encrypted at rest (AES-256-CBC)"
echo "  Binding:        ${GATEWAY_BIND} only (localhost)"
echo ""
echo "  The Telegram bot is now active."
echo ""
echo "=============================================="
